### ISSUE TITLE
Regarding Gradlew checks

### ISSUE THREAD

**Issue by JensonWee** [nus-cs2113-AY1920S2/tp#49]
I've runned on my terminal : "runtest.bat" and it showed test passed. However, during GitHub checks, I encounter this issue:

![image](https://user-images.githubusercontent.com/55829267/76686558-2d837800-6657-11ea-8047-b72819dd2ab8.png)

I can't really tell the error here.

**Comment by MeLoveCarbs** [comment]
I've also encountered this error despite both ASCII art showing the exact same thing. The problem is there are some unknown whitespace counted and not showing up. Go to https://www.diffchecker.com/ and it will show you where the extra/missing whitespace is in your EXPECTED.TXT.
Hope this helps :smile:

**Comment by JensonWee** [comment]
> I've also encountered this error despite both ASCII art showing the exact same thing. The problem is there are some unknown whitespace counted and not showing up. Go to https://www.diffchecker.com/ and it will show you where the extra/missing whitespace is in your EXPECTED.TXT.
> Hope this helps 😄

Thanks for the tip, @MeLoveCarbs ! But i found out the problem was how different OS handles the data in an arraylist. The order of the items in an arraylist for different os was culprit for my issue. Fixed it by sorting the arraylist before printing, thus, solving the runtest issue.
